@baseUrl = https://cse341-project2-o5vk.onrender.com

### GET ALL DIRECTORS
GET {{baseUrl}}/directors

### GET DIRECTOR BY ID
GET {{baseUrl}}/directors/691890fce6a3dda8daba3f6f

### CREATE DIRECTOR
POST {{baseUrl}}/directors
Content-Type: application/json

{
  "name": "Mariona Suncion",
  "birthYear": 1980,
  "nationality": "French"
}

### UPDATE DIRECTOR
PUT {{baseUrl}}/directors/691890fce6a3dda8daba3f6f
Content-Type: application/json

{
  "name": "Christopher Nolan",
  "birthYear": 1970,
  "nationality": "British-peruvian"
}

### DELETE DIRECTOR
DELETE {{baseUrl}}/directors/{id}
